"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
from setuptools import setup

SETUP_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.abspath(os.path.join(SETUP_DIR, os.pardir))

APP = [os.path.join(BASE_DIR, 'main.py')]
DATA_FILES = [os.path.join(BASE_DIR,'bin'), os.path.join(BASE_DIR,'html')]
OPTIONS = {'iconfile': os.path.join(SETUP_DIR,'phantom.icns')}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
